### ISSUE TITLE
Error when sending batch messages - Postmark::TimeoutError (Net::ReadTimeout)

### ISSUE THREAD

**Issue by nicks6853** [ActiveCampaign/postmark-gem#129]
Hello,

We've been using postmark at our company for a little while and recently ran into this problem.
Our clients send out newsletter through a Rails website we built and we use Postmark::ApiClient to send messages in bulk using the deliver_messages() function. Around 3000 emails should be sent for every newsletter.

Recently, the Postmark::TimeoutError (Net::ReadTimeout) has been happening every time a newsletter is sent out, and only 1000 - 1500 of the 3000 emails make it to Postmark.

The application had not been updated since earlier this year, and everything had been working fine until it happened on July 20th, then didn't happen until October 4th and since then it has happened everytime they try to send out emails in bulk.

This is the code that takes care of sending the emails:
```ruby
client = Postmark::ApiClient.new(Rails.application.secrets.postmark_api_token)
messages = emails.map { |email| NewsletterMailer.newsletter(email, @newsletter) }
client.deliver_messages(messages) if Rails.env == "production"
```

Does anyone have any insight on why this could be happening? I get what a timeout error is, but nothing related to networking has changed on our server as far as we are aware and this started happening.

Here is a sample of the error from the logs
```
E, [2022-10-04T11:50:31.024907 #31542] ERROR -- : [ActiveJob] [SendNewsletter] [8a63ff10-a576-4893-abc0-51102c6cca86] Error performing SendNewsletter (Job ID: 8a63ff10-a576-4893-abc0-51102c6cca86) from Async(default) in 21860.9ms: Postmark::TimeoutError (Net::ReadTimeout):
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/http_client.rb:95:in `rescue in do_request'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/http_client.rb:90:in `do_request'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/http_client.rb:32:in `post'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/api_client.rb:69:in `block (2 levels) in deliver_messages'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/client.rb:39:in `with_retries'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/api_client.rb:68:in `block in deliver_messages'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/api_client.rb:382:in `block in in_batches'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/api_client.rb:381:in `each'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/api_client.rb:381:in `each_slice'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/api_client.rb:381:in `each_with_index'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/api_client.rb:381:in `each'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/api_client.rb:381:in `map'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/api_client.rb:381:in `in_batches'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/postmark-1.22.1/lib/postmark/api_client.rb:65:in `deliver_messages'
/home/sanb/rails_app/app/jobs/send_newsletter.rb:9:in `block in perform'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/core_ext/array/grouping.rb:37:in `block in in_groups_of'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/core_ext/array/grouping.rb:37:in `each'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/core_ext/array/grouping.rb:37:in `each_slice'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/core_ext/array/grouping.rb:37:in `in_groups_of'
/home/sanb/rails_app/app/jobs/send_newsletter.rb:7:in `perform'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/execution.rb:37:in `block in perform_now'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/i18n-0.9.5/lib/i18n.rb:268:in `with_locale'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/logging.rb:44:in `block in tag_logger'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/logging.rb:44:in `tag_logger'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/execution.rb:33:in `perform_now'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/execution.rb:22:in `block in execute'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/reloader.rb:68:in `block in wrap'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/reloader.rb:67:in `wrap'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/execution.rb:20:in `execute'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/activejob-5.1.7/lib/active_job/queue_adapters/async_adapter.rb:68:in `perform'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/home/sanb/.gem/ruby/ruby-2.7.6/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'

```

**Comment by justinpchang** [comment]
I am attempting a similar task and got the same error. After repeated testing, the error seemed to go away on its own. However, I was unable to send 500 emails per batch as per the docs; I would try to send 500 emails in one api request, and it would return successful with 0 error code but in Postmark Activity, it seemed only the first 10 emails per batch would send. I ended up having to decrease my batch size to 10 in order for all emails to send. Not sure what the problem is, but hope this helps @nicks6853

**Comment by MSeneadza** [comment]
I've also started getting a lot of timeouts, although I am not batch sending.  I queue up a few hundred emails in Sidekiq & they get sent individually.  (There could be up to a dozen Sidekiq workers sending at the same time though.). I've been doing it this way for a few years and I don't think I'd ever gotten a timeout before this month.

> Postmark::TimeoutError: Net::OpenTimeout (Most recent call first)
Hide 106 non-project frames
File /opt/render/project/.gems/ruby/3.1.0/gems/postmark-1.22.1/lib/postmark/http_client.rb:95 in rescue in do_request
File /opt/render/project/.gems/ruby/3.1.0/gems/postmark-1.22.1/lib/postmark/http_client.rb:90 in do_request
File /opt/render/project/.gems/ruby/3.1.0/gems/postmark-1.22.1/lib/postmark/http_client.rb:32 in post
File /opt/render/project/.gems/ruby/3.1.0/gems/postmark-1.22.1/lib/postmark/api_client.rb:38 in block (2 levels) in deliver_message
File /opt/render/project/.gems/ruby/3.1.0/gems/postmark-1.22.1/lib/postmark/client.rb:58 in take_response_of
File /opt/render/project/.gems/ruby/3.1.0/gems/postmark-1.22.1/lib/postmark/api_client.rb:38 in block in deliver_message
File /opt/render/project/.gems/ruby/3.1.0/gems/postmark-1.22.1/lib/postmark/client.rb:39 in with_retries
File /opt/render/project/.gems/ruby/3.1.0/gems/postmark-1.22.1/lib/postmark/api_client.rb:37 in deliver_message
File /opt/render/project/.gems/ruby/3.1.0/gems/postmark-1.22.1/lib/postmark/handlers/mail.rb:14 in deliver!
File /opt/render/project/.gems/ruby/3.1.0/gems/mail-2.7.1/lib/mail/message.rb:2159 in do_delivery
File /opt/render/project/.gems/ruby/3.1.0/gems/mail-2.7.1/lib/mail/message.rb:260 in block in deliver
File /opt/render/project/.gems/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:588 in block in deliver_mail
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206 in block in instrument
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb:24 in instrument
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206 in instrument
File /opt/render/project/.gems/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:586 in deliver_mail
File /opt/render/project/.gems/ruby/3.1.0/gems/mail-2.7.1/lib/mail/message.rb:260 in deliver
File /opt/render/project/.gems/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/message_delivery.rb:119 in block in deliver_now
File /opt/render/project/.gems/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/rescuable.rb:17 in handle_exceptions
File /opt/render/project/.gems/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/message_delivery.rb:118 in deliver_now
File /opt/render/project/.gems/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/mail_delivery_job.rb:23 in perform
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/execution.rb:59 in block in _perform_job
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:118 in block in run_callbacks
File /opt/render/project/.gems/ruby/3.1.0/gems/newrelic_rpm-8.11.0/lib/new_relic/agent/instrumentation/active_job.rb:54 in perform
File /opt/render/project/.gems/ruby/3.1.0/gems/newrelic_rpm-8.11.0/lib/new_relic/agent/instrumentation/active_job.rb:23 in block (4 levels) in <main>
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127 in instance_exec
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127 in block in run_callbacks
File /opt/render/project/.gems/ruby/3.1.0/gems/i18n-1.12.0/lib/i18n.rb:322 in with_locale
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/translation.rb:9 in block (2 levels) in <module:Translation>
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127 in instance_exec
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127 in block in run_callbacks
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/core_ext/time/zones.rb:66 in use_zone
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/timezones.rb:9 in block (2 levels) in <module:Timezones>
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127 in instance_exec
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127 in block in run_callbacks
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:138 in run_callbacks
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/execution.rb:58 in _perform_job
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:20 in _perform_job
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/execution.rb:46 in perform_now
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:14 in block in perform_now
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:25 in block in instrument
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206 in block in instrument
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb:24 in instrument
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206 in instrument
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:35 in instrument
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:14 in perform_now
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/logging.rb:18 in block in perform_now
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:99 in block in tagged
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:37 in tagged
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:99 in tagged
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/logging.rb:25 in tag_logger
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/logging.rb:18 in perform_now
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/execution.rb:24 in block in execute
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:118 in block in run_callbacks
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/railtie.rb:54 in block (4 levels) in <class:Railtie>
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92 in wrap
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/reloader.rb:72 in block in wrap
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:88 in wrap
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/reloader.rb:71 in wrap
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/railtie.rb:53 in block (3 levels) in <class:Railtie>
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127 in instance_exec
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127 in block in run_callbacks
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:138 in run_callbacks
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/execution.rb:22 in execute
File /opt/render/project/.gems/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:42 in perform
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:202 in execute_job
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:170 in block (2 levels) in process
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:177 in block in invoke
File /opt/render/project/.gems/ruby/3.1.0/gems/rollbar-3.3.1/lib/rollbar/plugins/sidekiq/plugin.rb:11 in call
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:179 in block in invoke
File /opt/render/project/.gems/ruby/3.1.0/gems/ros-apartment-sidekiq-1.2.0/lib/apartment/sidekiq/middleware/server.rb:5 in block in call
File /opt/render/project/.gems/ruby/3.1.0/bundler/gems/apartment-f779996f7021/lib/apartment/adapters/abstract_adapter.rb:89 in switch
File /opt/render/project/rubies/ruby-3.1.0/lib/ruby/3.1.0/forwardable.rb:238 in switch
File /opt/render/project/.gems/ruby/3.1.0/gems/ros-apartment-sidekiq-1.2.0/lib/apartment/sidekiq/middleware/server.rb:4 in call
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:179 in block in invoke
File /opt/render/project/.gems/ruby/3.1.0/gems/newrelic_rpm-8.11.0/lib/new_relic/agent/instrumentation/sidekiq.rb:36 in block in call
File /opt/render/project/.gems/ruby/3.1.0/gems/newrelic_rpm-8.11.0/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:382 in perform_action_with_newrelic_trace
File /opt/render/project/.gems/ruby/3.1.0/gems/newrelic_rpm-8.11.0/lib/new_relic/agent/instrumentation/sidekiq.rb:31 in call
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:179 in block in invoke
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-failures-1.0.4/lib/sidekiq/failures/middleware.rb:9 in call
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:179 in block in invoke
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:182 in invoke
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:169 in block in process
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:136 in block (6 levels) in dispatch
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/job_retry.rb:113 in local
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:135 in block (5 levels) in dispatch
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/rails.rb:14 in block in call
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92 in wrap
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/reloader.rb:72 in block in wrap
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92 in wrap
File /opt/render/project/.gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/reloader.rb:71 in wrap
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/rails.rb:13 in call
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:131 in block (4 levels) in dispatch
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:263 in stats
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:126 in block (3 levels) in dispatch
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/job_logger.rb:13 in call
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:125 in block (2 levels) in dispatch
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/job_retry.rb:80 in global
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:124 in block in dispatch
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/job_logger.rb:39 in prepare
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:123 in dispatch
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:168 in process
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:78 in process_one
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:68 in run
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/component.rb:8 in watchdog
File /opt/render/project/.gems/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/component.rb:17 in block in safe_thread

**Comment by nicks6853** [comment]
I can confirm that reducing the batch size to a smaller number helped mitigate the issue. Sending in batches of 400 or 500 didn't work but 250 seems to be working. Still, it seems that there is an issue since it only started doing this in the last month or so. Would be nice to get some input from the ActiveCampaign team.

**Comment by JordoLoveDonut** [comment]
Hi @nicks6853,

Jordan from Postmark here! Thanks for the heads up on this. We have been able to mitigate an issue that was contributing to the recurring API timeouts you were experiencing in the past weeks. We have not seen any new occurrences of such timeouts in the last 36 hours or so, but we are continuing to monitor.

The team will continue to investigate and ensure that a permanent fix is in place to help avoid something like this happening in the future.

If you continue to see issues sending in batches of 500 or see similar timeouts, please write into our support team [here](https://postmarkapp.com/contact) and we'll be happy to help take a look. Thanks so much! 💛

**Comment by nicks6853** [comment]
Awesome, thanks!
