### ISSUE TITLE
Postmark::ApiInputError: Error parsing 'To': Illegal email domain 'yahoo.com.' in address

### ISSUE THREAD

**Issue by arifb** [ActiveCampaign/postmark-gem#138]
Hi, please see subject. 

We can’t send mail to yahoo.com addresses??

**Comment by balvig** [comment]
@arifb from the shared error message, it looks like maybe there's an additional `.` at the end of the domain name (ie `yahoo.com.`).

Could you maybe double check whether this is the case? 

There shouldn't be any restrictions on sending email to yahoo.com domains, but let me know how you get on, perhaps something else is going on!
