### ISSUE TITLE
Postmark::AccountApiClient mutates "options" argument 

### ISSUE THREAD

**Issue by kyakaze** [ActiveCampaign/postmark-gem#153]
Hi team,
Currently `Postmark::AccountApiClient` directly mutates the `options` argument which is not consistent with the `Postmark::ApiClient` and could cause runtime bug.

With the example below, when using `account_client` and `server_client` alternately in the same server instance, `OPTIONS` would be mutated due to this code `options[:auth_header_name] = 'X-Postmark-Account-Token'` in the initializer of `Postmark::AccountApiClient` causing `server_client` sending requests with header `:auth_header_name => 'X-Postmark-Account-Token'`
```
OPTIONS =  {
      secure: true,
      http_open_timeout: 5,
      http_read_timeout: 5,
    }

account_client = Postmark::AccountApiClient.new(ENV['postmark_account_api_key'], OPTIONS)
server_client = Postmark::ApiClient.new(ENV['postmark_server_api_key'], OPTIONS)
```

Expected behaviour:  Should dup the options in `Postmark::AccountApiClient` just like how it is done in `Postmark::ApiClient`

**Comment by balvig** [comment]
Thank you @kyakaze! Great catch 👍 
Addressing this in #154
