### ISSUE TITLE
Validation of email address

### ISSUE THREAD

**Issue by nicholas-johnson** [ActiveCampaign/postmark-gem#30]
It would be great to be able to validate an email against the same regex that Postmark uses, something like:

```
class User
  validates_format_of :email, with: Postmark.regex
end
```

**Comment by SimonHausdorf** [comment]
Is email validation still planned?

**Comment by FYJen** [comment]
Bump. Looking for this solution from Postmark.

**Comment by paulhtrott** [comment]
Bump. Looking for this as well. Something similar to Mailguns api endpoint for email validation. “Deliverable vs Undeliverable” and “reason”. 

https://documentation.mailgun.com/en/latest/api-email-validation.html#email-validation

**Comment by anulaibar** [comment]
Here's the regex PM uses for validation - would be a nice addtion to the API to add an endpoint for validation, or even better as @nicholas-johnson suggests, add it to the lib. I'm currently using community python lib https://github.com/xsleonard/pystmark so I guess I'll have to submit a PR... 🤔 

https://postmarkapp.com/support/article/1180-what-does-errorcode-300-mean

```
Domain: ^((\.)?[a-zA-Z0-9\-])+$
Mailbox: ^[a-z0-9\.!#\$%&'`\*\+\-\/=\^_\{\}\|~]+$
```

**Comment by parhs** [comment]
> Here's the regex PM uses for validation - would be a nice addtion to the API to add an endpoint for validation, or even better as @nicholas-johnson suggests, add it to the lib. I'm currently using community python lib https://github.com/xsleonard/pystmark so I guess I'll have to submit a PR... thinking
> 
> https://postmarkapp.com/support/article/1180-what-does-errorcode-300-mean
> 
> ```
> Domain: ^((\.)?[a-zA-Z0-9\-])+$
> Mailbox: ^[a-z0-9\.!#\$%&'`\*\+\-\/=\^_\{\}\|~]+$
> ```

There are some domains with non latin characters. I do not know whether postmark supports them though
